import mongoose from "mongoose";

/**
 * A point one person captured while working through a tender — from a clause,
 * from a chat answer, or typed free-hand. Notes are PRIVATE to their author;
 * only a super admin can read someone else's (see requireOwnerOrAdmin).
 *
 * Kept separate from Clause on purpose: a clause is what the model found in
 * the document and can be regenerated by re-running extraction, while a note
 * is a person's own judgement and must survive every re-run untouched.
 */
const NoteSchema = new mongoose.Schema(
  {
    tenderId: { type: mongoose.Schema.Types.ObjectId, ref: "Tender", required: true, index: true },
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    category: { type: String, index: true }, // optional: which section it relates to
    title: { type: String, required: true },
    text: { type: String, required: true },
    importance: { type: String, enum: ["critical", "high", "medium", "low"], default: "high" },
    // Where this note came from, so the UI can show provenance
    source: { type: String, enum: ["clause", "chat", "manual"], default: "manual" },
    clauseId: { type: mongoose.Schema.Types.ObjectId, ref: "Clause" }, // source: "clause"
    askedQuestion: String, // source: "chat" — the question that produced it
    // Citation back into the PDF, copied from the clause or chat answer
    sourceFile: String,
    page: Number,
    // Set when this note was also compressed into the shared executive brief
    inExecSummary: { type: Boolean, default: false },
  },
  { timestamps: true }
);

NoteSchema.index({ tenderId: 1, userId: 1, createdAt: -1 });

export const Note = mongoose.model("Note", NoteSchema);
